'use client';
import {useMemo,useState} from 'react';

type Job={id:number;role:string;company:string;location:string;mode:string;salary:string;match:number;logo:string;skills:string[]};
const jobs:Job[]=[
{id:1,role:'Product Designer',company:'Nova Labs',location:'Bengaluru, India',mode:'Hybrid',salary:'₹12–18 LPA',match:96,logo:'N',skills:['Figma','UX Research','Design Systems']},
{id:2,role:'Frontend Engineer',company:'Orbit Systems',location:'Remote · India',mode:'Remote',salary:'₹10–16 LPA',match:93,logo:'O',skills:['React','TypeScript','Next.js']},
{id:3,role:'AI Product Manager',company:'Vertex AI',location:'Bengaluru, India',mode:'On-site',salary:'₹18–26 LPA',match:89,logo:'V',skills:['AI/ML','Product Strategy','SQL']},
{id:4,role:'Data Analyst',company:'Pulse Finance',location:'Mumbai, India',mode:'Hybrid',salary:'₹7–11 LPA',match:86,logo:'P',skills:['Python','SQL','Power BI']},
{id:5,role:'UX Researcher',company:'Mosaic',location:'Remote · India',mode:'Remote',salary:'₹9–14 LPA',match:91,logo:'M',skills:['Research','Figma','Interviews']},
{id:6,role:'Growth Marketing Manager',company:'Lumen',location:'Delhi NCR',mode:'Hybrid',salary:'₹11–17 LPA',match:82,logo:'L',skills:['Growth','Analytics','SEO']}];
const tabs=['Dashboard','Career Plan','Resume AI','Interview Coach','Jobs'];
export default function Home(){const[tab,setTab]=useState('Dashboard');const[query,setQuery]=useState('');const[saved,setSaved]=useState<number[]>([]);const[toast,setToast]=useState('');const[resume,setResume]=useState(false);const[interview,setInterview]=useState(false);const[progress,setProgress]=useState(64);
const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),1800)};const filtered=useMemo(()=>jobs.filter(j=>(j.role+' '+j.company+' '+j.skills.join(' ')).toLowerCase().includes(query.toLowerCase())),[query]);
const complete=()=>{setProgress(p=>Math.min(100,p+8));notify('Career milestone completed')};
return <main><aside className="sidebar"><div className="brand"><span className="mark">✦</span><span>CareerPilot <b>AI</b></span></div><div className="profile"><div className="avatar">VD</div><div><b>Career Explorer</b><small>Personal workspace</small></div></div><nav>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><span>{t==='Dashboard'?'⌂':t==='Career Plan'?'◎':t==='Resume AI'?'▤':t==='Interview Coach'?'◉':'⌕'}</span>{t}</button>)}</nav><div className="sideCard"><span>✦</span><b>AI Career Score</b><strong>78<span>/100</span></strong><small>↑ 12% this month</small><div className="miniBar"><i/></div></div><div className="sideBottom"><button onClick={()=>notify('Settings panel ready')}>⚙ Settings</button><button onClick={()=>notify('Help center ready')}>? Help center</button></div></aside>
<section className="app"><header><div><span className="mobileTitle">CareerPilot AI</span><p>Wednesday, August 26 · Keep building your future.</p></div><div className="headActions"><button onClick={()=>notify('3 new career insights available')}>♧ <i>3</i></button><div className="user">VD</div></div></header>
<div className="content"><div className="welcome"><div><span className="eyebrow">YOUR CAREER COMMAND CENTER</span><h1>Good evening, <em>Career Explorer.</em></h1><p>Here’s what matters most for your next career move.</p></div><button className="primary" onClick={()=>{setTab('Career Plan');notify('Career plan opened')}}>✦ View my plan</button></div>
<div className="scoreGrid"><div className="scoreCard"><div className="scoreCircle"><strong>{progress}</strong><span>/100</span></div><div><b>Career readiness</b><p>You're ahead of 72% of similar profiles.</p><div className="bar"><i style={{width:progress+'%'}}/></div><small>+8 points to reach your next milestone</small></div></div><div className="stat"><span>🎯</span><div><small>Next milestone</small><b>Senior-level ready</b><p>3 skills remaining</p></div></div><div className="stat"><span>🔥</span><div><small>Market demand</small><b>Very high</b><p>For your target roles</p></div></div></div>
<div className="sectionHead"><div><h2>Today's action plan</h2><p>Small steps compound into big career moves.</p></div><button onClick={complete}>Mark next complete →</button></div><div className="actions"><article className="action done"><div className="check">✓</div><div><span>RESUME</span><h3>Strengthen your impact statements</h3><p>Turn responsibilities into measurable achievements.</p></div><button onClick={()=>setResume(true)}>Review →</button></article><article className="action"><div className="check">2</div><div><span>SKILL BUILDING</span><h3>Complete a TypeScript challenge</h3><p>15 min · Builds your Frontend Engineer readiness.</p></div><button onClick={complete}>Start →</button></article><article className="action"><div className="check">3</div><div><span>INTERVIEW</span><h3>Practice your “Tell me about yourself”</h3><p>AI feedback · 5 min</p></div><button onClick={()=>setInterview(true)}>Practice →</button></article></div>
<div className="sectionHead jobsHead"><div><h2>Jobs matched to you</h2><p>AI-ranked using your skills, goals and preferences.</p></div><button onClick={()=>setTab('Jobs')}>See all jobs →</button></div><div className="jobSearch"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles, companies or skills..."/></div><div className="jobs">{filtered.slice(0,4).map(j=><article className="job" key={j.id}><div className="companyLogo">{j.logo}</div><div className="jobMain"><div><h3>{j.role}</h3><p>{j.company} · {j.location}</p></div><span className="match">{j.match}% match</span><div className="chips">{j.skills.map(s=><span key={s}>{s}</span>)}<span>{j.mode}</span></div><small>{j.salary}</small></div><button className="save" onClick={()=>{setSaved(s=>s.includes(j.id)?s.filter(x=>x!==j.id):[...s,j.id]);notify(saved.includes(j.id)?'Removed from saved':'Job saved')}}>{saved.includes(j.id)?'♥':'♡'}</button></article>)}</div>
<div className="bottomGrid"><div className="insight"><span className="spark">✦</span><div><b>AI insight for you</b><h3>Product + AI is your strongest opportunity zone.</h3><p>Your current skills overlap strongly with a growing set of AI product roles. Adding one portfolio project could increase your match rate significantly.</p><button onClick={()=>notify('AI learning path opened')}>Explore learning path →</button></div></div><div className="weekly"><div><b>Weekly momentum</b><span>{progress}%</span></div><div className="weekbar"><i style={{width:progress+'%'}}/></div><p>4 of 6 weekly goals completed</p></div></div></div></section>
{resume&&<div className="modal" onClick={()=>setResume(false)}><div className="modalCard" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setResume(false)}>×</button><span className="eyebrow">RESUME AI</span><h2>Make your experience stand out.</h2><p>Paste a resume bullet and CareerPilot will suggest a stronger, achievement-focused version.</p><textarea defaultValue="Worked on the company website and improved user experience."/><button className="primary" onClick={()=>{setResume(false);notify('AI improved your resume bullet')}}>✦ Improve with AI</button></div></div>}
{interview&&<div className="modal" onClick={()=>setInterview(false)}><div className="modalCard" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setInterview(false)}>×</button><span className="eyebrow">INTERVIEW COACH</span><h2>Tell me about yourself.</h2><p>Take 60 seconds to answer. In a full AI integration, your response would be scored on clarity, relevance and confidence.</p><textarea placeholder="Type your answer here..."/><button className="primary" onClick={()=>{setInterview(false);notify('Practice response submitted — great start!')}}>Submit practice →</button></div></div>}
{toast&&<div className="toast">✓ {toast}</div>}</main>}
